// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCApNyYM4UF1huw3UqZJI4svADehvu9ZtQ',
    appId: '1:296098370114:web:37d6bc04e39bf682e5d3db',
    messagingSenderId: '296098370114',
    projectId: 'prods-fdfa0',
    authDomain: 'prods-fdfa0.firebaseapp.com',
    storageBucket: 'prods-fdfa0.appspot.com',
    measurementId: 'G-XCW585RYPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWfOv9tCsVf7luwDiH4GoMJeM3uewYFVg',
    appId: '1:296098370114:android:e62497b97875780de5d3db',
    messagingSenderId: '296098370114',
    projectId: 'prods-fdfa0',
    storageBucket: 'prods-fdfa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsv0KxVABtBWNJBm4gyr39UUiU6PHt7hg',
    appId: '1:296098370114:ios:381519f34fca405ae5d3db',
    messagingSenderId: '296098370114',
    projectId: 'prods-fdfa0',
    storageBucket: 'prods-fdfa0.appspot.com',
    iosBundleId: 'com.mrz.prods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsv0KxVABtBWNJBm4gyr39UUiU6PHt7hg',
    appId: '1:296098370114:ios:381519f34fca405ae5d3db',
    messagingSenderId: '296098370114',
    projectId: 'prods-fdfa0',
    storageBucket: 'prods-fdfa0.appspot.com',
    iosBundleId: 'com.mrz.prods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCApNyYM4UF1huw3UqZJI4svADehvu9ZtQ',
    appId: '1:296098370114:web:fbeae70e0c42b93be5d3db',
    messagingSenderId: '296098370114',
    projectId: 'prods-fdfa0',
    authDomain: 'prods-fdfa0.firebaseapp.com',
    storageBucket: 'prods-fdfa0.appspot.com',
    measurementId: 'G-6HG6BEZTKQ',
  );

}